version = 1

test_patterns = [
  "**/*.spec.*",
  "apps/*-e2e/**"
]

exclude_patterns = [
  "android/**",
  "ios/*/capacitor-cordova-ios-plugins"
]

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]

[[transformers]]
name = "prettier"

[[transformers]]
name = "rustfmt"