version = 1

test_patterns = ["tests/**"]

exclude_patterns = ["node_modules/"]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]

[[transformers]]
name = "prettier"