require_relative '../../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../../node_modules/@capacitor/app'
  pod 'CapacitorBrowser', :path => '../../../node_modules/@capacitor/browser'
  pod 'CapacitorPreferences', :path => '../../../node_modules/@capacitor/preferences'
  pod 'CapacitorNetwork', :path => '../../../node_modules/@capacitor/network'
  pod 'CapacitorFilesystem', :path => '../../../node_modules/@capacitor/filesystem'
  pod 'CapacitorShare', :path => '../../../node_modules/@capacitor/share'
  pod 'CapacitorPushNotifications', :path => '../../../node_modules/@capacitor/push-notifications'
  pod 'CapacitorLocalNotifications', :path => '../../../node_modules/@capacitor/local-notifications'
  pod 'CapacitorSplashScreen', :path => '../../../node_modules/@capacitor/splash-screen'
  pod 'CapawesomeCapacitorAppUpdate', :path => '../../../node_modules/@capawesome/capacitor-app-update'
  pod 'CapacitorMlkitTranslation', :path => '../../../node_modules/@capacitor-mlkit/translation'
  pod 'CapacitorCommunityScreenBrightness', :path => '../../../node_modules/@capacitor-community/screen-brightness'
  pod 'CapacitorCommunityFirebaseCrashlytics', :path => '../../../node_modules/@capacitor-community/firebase-crashlytics'
end

def firebase_pods
  pod 'FirebaseAnalytics'

  pod 'FirebaseCrashlytics'
  pod 'FirebaseMessaging'
  pod 'FirebasePerformance'
end

target 'App' do
  capacitor_pods
  firebase_pods
end

target 'pushextension' do
  firebase_pods
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
