require_relative '../../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../node_modules/.pnpm/@capacitor+ios@4.8.0_@capacitor+core@4.8.0/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../node_modules/.pnpm/@capacitor+ios@4.8.0_@capacitor+core@4.8.0/node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../../node_modules/.pnpm/@capacitor+app@4.1.1_@capacitor+core@4.8.0/node_modules/@capacitor/app'
  pod 'CapacitorBrowser', :path => '../../../node_modules/.pnpm/@capacitor+browser@4.1.1_@capacitor+core@4.8.0/node_modules/@capacitor/browser'
  pod 'CapacitorPreferences', :path => '../../../node_modules/.pnpm/@capacitor+preferences@4.0.2_@capacitor+core@4.8.0/node_modules/@capacitor/preferences'
  pod 'CapacitorNetwork', :path => '../../../node_modules/.pnpm/@capacitor+network@4.1.0_@capacitor+core@4.8.0/node_modules/@capacitor/network'
  pod 'CapacitorFilesystem', :path => '../../../node_modules/.pnpm/@capacitor+filesystem@4.1.5_@capacitor+core@4.8.0/node_modules/@capacitor/filesystem'
  pod 'CapacitorShare', :path => '../../../node_modules/.pnpm/@capacitor+share@4.1.1_@capacitor+core@4.8.0/node_modules/@capacitor/share'
  pod 'CapacitorPushNotifications', :path => '../../../node_modules/.pnpm/@capacitor+push-notifications@4.1.2_@capacitor+core@4.8.0/node_modules/@capacitor/push-notifications'
  pod 'CapacitorLocalNotifications', :path => '../../../node_modules/.pnpm/@capacitor+local-notifications@4.1.5_@capacitor+core@4.8.0/node_modules/@capacitor/local-notifications'
  pod 'CapacitorSplashScreen', :path => '../../../node_modules/.pnpm/@capacitor+splash-screen@4.2.0_@capacitor+core@4.8.0/node_modules/@capacitor/splash-screen'
  pod 'CapawesomeCapacitorAppUpdate', :path => '../../../node_modules/.pnpm/@capawesome+capacitor-app-update@2.1.1_@capacitor+core@4.8.0/node_modules/@capawesome/capacitor-app-update'
  pod 'CapacitorMlkitTranslation', :path => '../../../node_modules/.pnpm/@capacitor-mlkit+translation@0.0.3_@capacitor+core@4.8.0/node_modules/@capacitor-mlkit/translation'
  pod 'CapacitorCommunityScreenBrightness', :path => '../../../node_modules/.pnpm/@capacitor-community+screen-brightness@4.0.0_@capacitor+core@4.8.0/node_modules/@capacitor-community/screen-brightness'
end

def firebase_pods
  pod 'FirebaseAnalytics'

  pod 'FirebaseCrashlytics'
  pod 'FirebaseMessaging'
  pod 'FirebasePerformance'
end

target 'App' do
  capacitor_pods
  firebase_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
